//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StableDiffusionDiscordBot.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StableDiffusionDiscordBot.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   About Charges に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AboutCharges {
            get {
                return ResourceManager.GetString("AboutCharges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   What is this site? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AboutSite {
            get {
                return ResourceManager.GetString("AboutSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A. Discord account and credit card information cannot be verified directly by the site&apos;s creator. The site is also publicly available on に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AccessInfomationAnswer1 {
            get {
                return ResourceManager.GetString("AccessInfomationAnswer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GitHub に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AccessInfomationAnswer2 {
            get {
                return ResourceManager.GetString("AccessInfomationAnswer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   so you can be sure they are not doing anything suspicious. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AccessInfomationAnswer3 {
            get {
                return ResourceManager.GetString("AccessInfomationAnswer3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Q. Maybe they&apos;ll pull out your Discord account or credit card info? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AccessInfomationQuestion {
            get {
                return ResourceManager.GetString("AccessInfomationQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add Bot に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AddBot {
            get {
                return ResourceManager.GetString("AddBot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Adding a Bot to the Discord Server に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AddBotDiscord {
            get {
                return ResourceManager.GetString("AddBotDiscord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Generates higher quality images than NobelAI or Waifu diffusion に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AnythingFeatures {
            get {
                return ResourceManager.GetString("AnythingFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A. Adding a bot to the Discord server is free. Please see the fee schedule above for generating images. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BillingAnswer {
            get {
                return ResourceManager.GetString("BillingAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Q. How much does it cost? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BillingQuestion {
            get {
                return ResourceManager.GetString("BillingQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Caution : The legal responsibility for the images generated by the Bot belongs to the generator. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Caution {
            get {
                return ResourceManager.GetString("Caution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Charge に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Charge {
            get {
                return ResourceManager.GetString("Charge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CustomerPortal に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CustomerPortal {
            get {
                return ResourceManager.GetString("CustomerPortal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   0 to 10 sheets に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FreeCount {
            get {
                return ResourceManager.GetString("FreeCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   US$0 (no usage fee) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FreePay {
            get {
                return ResourceManager.GetString("FreePay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The generated image is sent by reply from the bot. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GeneratedImageFromBot {
            get {
                return ResourceManager.GetString("GeneratedImageFromBot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   How to use the Bot に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HowToUseBot {
            get {
                return ResourceManager.GetString("HowToUseBot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   How to use this site に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HowToUseThisSite {
            get {
                return ResourceManager.GetString("HowToUseThisSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bot Language に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Login に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Login with your Discord account に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LoginWithDiscord {
            get {
                return ResourceManager.GetString("LoginWithDiscord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Logout に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use AI Model に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Number of images generated per month に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NumberOfImages {
            get {
                return ResourceManager.GetString("NumberOfImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A. Please contact the developer&apos;s に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OtherProblemAnswer1 {
            get {
                return ResourceManager.GetString("OtherProblemAnswer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Twitter account に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OtherProblemAnswer2 {
            get {
                return ResourceManager.GetString("OtherProblemAnswer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   via reply or direct message. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OtherProblemAnswer3 {
            get {
                return ResourceManager.GetString("OtherProblemAnswer3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Q. Other problems like this happened. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OtherProblemQuestion {
            get {
                return ResourceManager.GetString("OtherProblemQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Send a reply to the bot you want to use on Discord に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SendDiscordToBot {
            get {
                return ResourceManager.GetString("SendDiscordToBot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sign up for a subscription に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SignUpSubscription {
            get {
                return ResourceManager.GetString("SignUpSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You can add a bot to Discord that performs AI-based image generation. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SiteDescription {
            get {
                return ResourceManager.GetString("SiteDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stable Diffusion can produce higher resolution images. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StableDiffusion2Features {
            get {
                return ResourceManager.GetString("StableDiffusion2Features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Many types of images can be generated, including people and backgrounds に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StableDiffusionFeatures {
            get {
                return ResourceManager.GetString("StableDiffusionFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sign up Subscription に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Subscription {
            get {
                return ResourceManager.GetString("Subscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   11 sheets~. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SubscriptionCount {
            get {
                return ResourceManager.GetString("SubscriptionCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You do not have a subscription, に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SubscriptionDisableDescription1 {
            get {
                return ResourceManager.GetString("SubscriptionDisableDescription1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   please sign up for a subscription to start using Bot. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SubscriptionDisableDescription2 {
            get {
                return ResourceManager.GetString("SubscriptionDisableDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You have multiple subscriptions. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SubscriptionDuplicationDescription1 {
            get {
                return ResourceManager.GetString("SubscriptionDuplicationDescription1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please check your subscription status in the Customer Portal as you may not have been billed correctly. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SubscriptionDuplicationDescription2 {
            get {
                return ResourceManager.GetString("SubscriptionDuplicationDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Thank you for signing up for a subscription, if you wish to terminate your use of the Bot, に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SubscriptionEnableDescription1 {
            get {
                return ResourceManager.GetString("SubscriptionEnableDescription1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   you can add the Bot to your Discord server to use AI image generation, に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SubscriptionEnableDescription2 {
            get {
                return ResourceManager.GetString("SubscriptionEnableDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   please terminate your subscription through the Customer Portal. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SubscriptionEnableDescription3 {
            get {
                return ResourceManager.GetString("SubscriptionEnableDescription3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A fee of US$ 0.01 is charged for each sheet used. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SubscriptionPay {
            get {
                return ResourceManager.GetString("SubscriptionPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   About the types of AI models that can be used に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TableDescription {
            get {
                return ResourceManager.GetString("TableDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Features に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TableHeaderFeatures {
            get {
                return ResourceManager.GetString("TableHeaderFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Model Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TableHeaderModelName {
            get {
                return ResourceManager.GetString("TableHeaderModelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Images specialized for two-dimensional bishojo illustrations can be generated. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WaifuDiffusionFeatures {
            get {
                return ResourceManager.GetString("WaifuDiffusionFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wait a while for the image to be generated に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WaitWhileGenerated {
            get {
                return ResourceManager.GetString("WaitWhileGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A. Please cancel your subscription through the Customer Portal button that appears after logging in on Discord. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WantToCancelSubscriptionAnswer {
            get {
                return ResourceManager.GetString("WantToCancelSubscriptionAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Q. I want to cancel my subscription. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WantToCancelSubscriptionQuestion {
            get {
                return ResourceManager.GetString("WantToCancelSubscriptionQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A. You will be billed for your subscription on a month-to-month basis upon signing up for a subscription. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WhenBilledAnswer {
            get {
                return ResourceManager.GetString("WhenBilledAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Q. When will I be billed? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WhenBilliedQuestion {
            get {
                return ResourceManager.GetString("WhenBilliedQuestion", resourceCulture);
            }
        }
    }
}
