//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StableDiffusionDiscordBot.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StableDiffusionDiscordBot.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Add Bot に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AddBot {
            get {
                return ResourceManager.GetString("AddBot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Generates higher quality images than NobelAI or Waifu diffusion に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AnythingFeatures {
            get {
                return ResourceManager.GetString("AnythingFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CustomerPortal に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CustomerPortal {
            get {
                return ResourceManager.GetString("CustomerPortal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bot Language に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Login に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Logout に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use AI Model に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stable Diffusion can produce higher resolution images. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StableDiffusion2Features {
            get {
                return ResourceManager.GetString("StableDiffusion2Features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Many types of images can be generated, including people and backgrounds に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StableDiffusionFeatures {
            get {
                return ResourceManager.GetString("StableDiffusionFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Register Subscription に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Subscription {
            get {
                return ResourceManager.GetString("Subscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   About the types of AI models that can be used に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TableDescription {
            get {
                return ResourceManager.GetString("TableDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Features に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TableHeaderFeatures {
            get {
                return ResourceManager.GetString("TableHeaderFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Model Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TableHeaderModelName {
            get {
                return ResourceManager.GetString("TableHeaderModelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Images specialized for two-dimensional bishojo illustrations can be generated. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WaifuDiffusionFeatures {
            get {
                return ResourceManager.GetString("WaifuDiffusionFeatures", resourceCulture);
            }
        }
    }
}
